### ISSUE TITLE
remove platform.system use tempfile 

### ISSUE THREAD

**Issue by sxslex** [sxslex/sxtools#11]
Remove platform.system use tempfile for creating directory for caching , if not passed the decorator.
line: 170-172

**Comment by cassiobotaro** [comment]
These lines? https://github.com/sxslex/sxtools/blob/master/sxtools/cache_def.py#L170-l172

**Comment by sxslex** [comment]
Nice !!! I did not know this feature to link the blades codes . Thank you.

**Comment by sxslex** [comment]
remove module
